$(document).ready ->
  $.get $('#hashtagTweets').val(), (data) ->
#    console.log 'Inside locationTweets'
    jsonHashtag= data.hashtag
    hashtagData= JSON.parse(jsonHashtag)
    tweets = hashtagData.tweets
    length = tweets.length
    console.log length
    i = 0
    while i < length
      $('<p>',
        text: tweets[i]).appendTo '#hashTagDiv'
      i++
    return
  return

# ---
# generated by js2coffee 2.2.0